### ISSUE TITLE
Allow API calls for files not within master branch

### ISSUE THREAD

**Issue by landonreed** [koopjs/geohub#4]
It's common for repos with web apps running on the `gh-pages` branch to store GeoJSON here rather than in the `master` branch.  Are there plans to add support for API calls to .geojson files in non-master branches?

**Comment by ngoldman** [comment]
Hi @landonreed, it's probably too little too late, but I'm working on a full rewrite of this package which should allow for adding your feature request more easily.

@chelm is it possible to transfer this repo over to koopjs and give me npm contributor access (https://www.npmjs.com/package/geohub) since it's solely a koop dependency and is in need of maintenance? I'll do the dirty work. :construction_worker:

**Comment by chelm** [comment]
@ngoldman ahh but of course! Will move it and make you a contributor today, thanks!

**Comment by chelm** [comment]
@ngoldman :checkered_flag: listo

**Comment by ngoldman** [comment]
@chelm woooo thanks.

@landonreed not sure if you're still interested but I'll try to get something in to support your use case in the next week or two.

**Comment by ngoldman** [comment]
Turns out that was pretty easy once I cleaned things up! Should be in the 1.0.0 release later today.

**Comment by ngoldman** [comment]
:v: https://github.com/koopjs/geohub/releases/tag/v1.0.0 :+1:

**Comment by chelm** [comment]
@ngoldman :dart: you rock!
